-- 키 제약조건 에 맞게  drop
DROP VIEW IF EXISTS COMVNUSERMASTER;

DROP TABLE IF EXISTS COMTNFILEDETAIL;
DROP TABLE IF EXISTS COMTNFILE;
DROP TABLE IF EXISTS COMTNSCHDULINFO;
DROP TABLE IF EXISTS COMTNBBS;
DROP TABLE IF EXISTS COMTNBBSUSE;
DROP TABLE IF EXISTS COMTNBBSMASTEROPTN;
DROP TABLE IF EXISTS COMTNBBSMASTER;
DROP TABLE IF EXISTS COMTNTMPLATINFO;
DROP TABLE IF EXISTS COMTNGNRLMBER;
DROP TABLE IF EXISTS COMTNENTRPRSMBER;
DROP TABLE IF EXISTS COMTNEMPLYRINFO;
DROP TABLE IF EXISTS COMTNAUTHORGROUPINFO;
DROP TABLE IF EXISTS COMTNORGNZTINFO;
DROP TABLE IF EXISTS COMTCCMMNDETAILCODE;
DROP TABLE IF EXISTS COMTCCMMNCODE;
DROP TABLE IF EXISTS COMTCCMMNCLCODE;
DROP TABLE IF EXISTS IDS;




CREATE TABLE IDS (
  TABLE_NAME varchar(20) NOT NULL,
  NEXT_ID decimal(30,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (TABLE_NAME)
) ;



CREATE TABLE COMTCCMMNCLCODE (
  CL_CODE CHAR(3) NOT NULL,
  CL_CODE_NM VARCHAR(60) NULL,
  CL_CODE_DC VARCHAR(200) NULL,
  USE_AT CHAR(1) NULL,
  FRST_REGIST_PNTTM DATETIME NULL,
  FRST_REGISTER_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  CONSTRAINT COMTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
);



CREATE TABLE COMTCCMMNCODE (
  CODE_ID VARCHAR(6) NOT NULL,
  CODE_ID_NM VARCHAR(60) NULL,
  CODE_ID_DC VARCHAR(200) NULL,
  USE_AT CHAR(1) NULL,
  CL_CODE CHAR(3) NULL,
  FRST_REGIST_PNTTM DATETIME NULL,
  FRST_REGISTER_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  CONSTRAINT COMTCCMMNCODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT COMTCCMMNCODE_FK1 FOREIGN KEY (CL_CODE) REFERENCES COMTCCMMNCLCODE(CL_CODE)
);



CREATE TABLE COMTCCMMNDETAILCODE (
  CODE_ID VARCHAR(6) NOT NULL,
  CODE VARCHAR(15) NOT NULL,
  CODE_NM VARCHAR(60) NULL,
  CODE_DC VARCHAR(200) NULL,
  USE_AT CHAR(1) NULL,
  FRST_REGIST_PNTTM DATETIME NULL,
  FRST_REGISTER_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  CONSTRAINT COMTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID, CODE),
  CONSTRAINT COMTCCMMNDETAILCODE_FK1 FOREIGN KEY (CODE_ID) REFERENCES COMTCCMMNCODE(CODE_ID)
);



CREATE TABLE COMTNORGNZTINFO (
  ORGNZT_ID VARCHAR(20) NOT NULL,
  ORGNZT_NM VARCHAR(20) NOT NULL,
  ORGNZT_DC VARCHAR(100) NULL,
  CONSTRAINT COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
);



CREATE TABLE COMTNAUTHORGROUPINFO (
  GROUP_ID CHAR(20) NOT NULL,
  GROUP_NM VARCHAR(60) NOT NULL,
  GROUP_CREAT_DE CHAR(20) NOT NULL,
  GROUP_DC VARCHAR(100) NULL,
  CONSTRAINT COMTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
);



CREATE TABLE COMTNEMPLYRINFO (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  ORGNZT_ID CHAR(20) NULL,
  USER_NM VARCHAR(60) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  EMPL_NO VARCHAR(20) NULL,
  IHIDNUM VARCHAR(200) NULL,
  SEXDSTN_CODE CHAR(1) NULL,
  BRTHDY CHAR(20) NULL,
  FXNUM VARCHAR(20) NULL,
  HOUSE_ADRES VARCHAR(100) NULL,
  PASSWORD_HINT VARCHAR(100) NOT NULL,
  PASSWORD_CNSR VARCHAR(100) NOT NULL,
  HOUSE_END_TELNO VARCHAR(4) NULL,
  AREA_NO VARCHAR(4) NULL,
  DETAIL_ADRES VARCHAR(100) NULL,
  ZIP VARCHAR(6) NULL,
  OFFM_TELNO VARCHAR(20) NULL,
  MBTLNUM VARCHAR(20) NULL,
  EMAIL_ADRES VARCHAR(50) NULL,
  OFCPS_NM VARCHAR(60) NULL,
  HOUSE_MIDDLE_TELNO VARCHAR(4) NULL,
  GROUP_ID CHAR(20) NULL,
  PSTINST_CODE CHAR(8) NULL,
  EMPLYR_STTUS_CODE VARCHAR(15) NULL,
  ESNTL_ID VARCHAR(20) NULL,
  CRTFC_DN_VALUE VARCHAR(100) NULL,
  SBSCRB_DE DATETIME NULL,
  CONSTRAINT COMTNEMPLYRINFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT COMTNEMPLYRINFO_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT COMTNEMPLYRINFO_FK2 FOREIGN KEY (ORGNZT_ID) REFERENCES COMTNORGNZTINFO(ORGNZT_ID) ON DELETE CASCADE
);



CREATE TABLE COMTNENTRPRSMBER (
  ENTRPRS_MBER_ID VARCHAR(20) NOT NULL,
  ENTRPRS_SE_CODE CHAR(15) NULL,
  BIZRNO VARCHAR(10) NULL,
  JURIRNO VARCHAR(13) NULL,
  CMPNY_NM VARCHAR(60) NOT NULL,
  CXFC VARCHAR(50) NULL,
  ZIP VARCHAR(6) NULL,
  ADRES VARCHAR(100) NULL,
  ENTRPRS_MIDDLE_TELNO VARCHAR(4) NULL,
  FXNUM VARCHAR(20) NULL,
  INDUTY_CODE CHAR(15) NULL,
  APPLCNT_NM VARCHAR(50) NULL,
  APPLCNT_IHIDNUM VARCHAR(200) NULL,
  SBSCRB_DE DATETIME NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  ENTRPRS_END_TELNO VARCHAR(4) NULL,
  AREA_NO VARCHAR(4) NULL,
  DETAIL_ADRES VARCHAR(100) NULL,
  ENTRPRS_TELNO VARCHAR(20) NULL,
  BXMSTR VARCHAR(60) NULL,
  GROUP_ID CHAR(20) NULL,
  ENTRPRS_MBER_STTUS VARCHAR(15) NULL,
  ENTRPRS_MBER_PASSWORD_HINT VARCHAR(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR VARCHAR(100) NOT NULL,
  ESNTL_ID VARCHAR(20) NULL,
  CONSTRAINT COMTNENTRPRSMBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT COMTNENTRPRSMBER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID) ON DELETE CASCADE
);



CREATE TABLE COMTNGNRLMBER (
  MBER_ID VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  PASSWORD_HINT VARCHAR(100) NOT NULL,
  PASSWORD_CNSR VARCHAR(100) NOT NULL,
  IHIDNUM VARCHAR(200) NULL,
  MBER_NM VARCHAR(50) NOT NULL,
  ZIP VARCHAR(6) NULL,
  ADRES VARCHAR(100) NULL,
  AREA_NO VARCHAR(4) NULL,
  MBER_STTUS VARCHAR(15) NULL,
  DETAIL_ADRES VARCHAR(100) NULL,
  END_TELNO VARCHAR(4) NULL,
  MBTLNUM VARCHAR(20) NULL,
  GROUP_ID CHAR(20) NULL,
  MBER_FXNUM VARCHAR(20) NULL,
  MBER_EMAIL_ADRES VARCHAR(50) NULL,
  MIDDLE_TELNO VARCHAR(4) NULL,
  SBSCRB_DE DATETIME NULL,
  SEXDSTN_CODE CHAR(1) NULL,
  ESNTL_ID VARCHAR(20) NULL,
  CONSTRAINT COMTNGNRLMBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT COMTNGNRLMBER_FK1 FOREIGN KEY (GROUP_ID) REFERENCES COMTNAUTHORGROUPINFO(GROUP_ID) ON DELETE CASCADE
);



CREATE TABLE COMTNTMPLATINFO (
  TMPLAT_ID CHAR(20) NOT NULL,
  TMPLAT_NM VARCHAR(255) NULL,
  TMPLAT_COURS VARCHAR(2000) NULL,
  USE_AT CHAR(1) NULL,
  TMPLAT_SE_CODE CHAR(6) NULL,
  FRST_REGISTER_ID VARCHAR(20) NULL,
  FRST_REGIST_PNTTM DATETIME NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  CONSTRAINT COMTNTMPLATINFO_PK PRIMARY KEY (TMPLAT_ID)
);



CREATE TABLE COMTNBBSMASTER (
  BBS_ID CHAR(20) NOT NULL,
  BBS_NM VARCHAR(255) NOT NULL,
  BBS_INTRCN VARCHAR(2400) NULL,
  BBS_TY_CODE CHAR(6) NOT NULL,
  BBS_ATTRB_CODE CHAR(6) NOT NULL,
  REPLY_POSBL_AT CHAR(1) NULL,
  FILE_ATCH_POSBL_AT CHAR(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER NUMERIC(2) NOT NULL,
  ATCH_POSBL_FILE_SIZE NUMERIC(8) NULL,
  USE_AT CHAR(1) NOT NULL,
  TMPLAT_ID CHAR(20) NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  CONSTRAINT COMTNBBSMASTER_PK PRIMARY KEY (BBS_ID),
  CONSTRAINT COMTNBBSMASTER_FK1 FOREIGN KEY (TMPLAT_ID) REFERENCES COMTNTMPLATINFO(TMPLAT_ID)
);



CREATE TABLE COMTNBBSMASTEROPTN (
  BBS_ID CHAR(20) NOT NULL,
  ANSWER_AT CHAR(1) NOT NULL,
  STSFDG_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  CONSTRAINT COMTNBBSMASTEROPTN_PK PRIMARY KEY (BBS_ID),
  CONSTRAINT COMTNBBSMASTEROPTN_FK1 FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
);



CREATE TABLE COMTNBBSUSE (
  BBS_ID CHAR(20) NOT NULL,
  TRGET_ID CHAR(20) NOT NULL,
  USE_AT CHAR(1) NOT NULL,
  REGIST_SE_CODE CHAR(6) NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  CONSTRAINT COMTNBBSUSE_PK PRIMARY KEY (BBS_ID, TRGET_ID),
  CONSTRAINT COMTNBBSUSE_FK1 FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
);



CREATE TABLE COMTNBBS (
  NTT_ID NUMERIC(20) NOT NULL,
  BBS_ID CHAR(20) NOT NULL,
  NTT_NO NUMERIC(20) NULL,
  NTT_SJ VARCHAR(2000) NULL,
  NTT_CN MEDIUMTEXT NULL,
  ANSWER_AT CHAR(1) NULL,
  PARNTSCTT_NO NUMERIC(10) NULL,
  ANSWER_LC NUMERIC(8) NULL,
  SORT_ORDR NUMERIC(8) NULL,
  RDCNT NUMERIC(10) NULL,
  USE_AT CHAR(1) NOT NULL,
  NTCE_BGNDE CHAR(20) NULL,
  NTCE_ENDDE CHAR(20) NULL,
  NTCR_ID VARCHAR(20) NULL,
  NTCR_NM VARCHAR(20) NULL,
  PASSWORD VARCHAR(200) NULL,
  ATCH_FILE_ID CHAR(20) NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM DATETIME NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  CONSTRAINT COMTNBBS_PK PRIMARY KEY (NTT_ID, BBS_ID),
  CONSTRAINT COMTNBBS_FK1 FOREIGN KEY (BBS_ID) REFERENCES COMTNBBSMASTER(BBS_ID)
);



CREATE TABLE COMTNSCHDULINFO (
  SCHDUL_ID CHAR(20) NOT NULL,
  SCHDUL_SE CHAR(1) NULL,
  SCHDUL_DEPT_ID VARCHAR(20) NULL,
  SCHDUL_KND_CODE VARCHAR(20) NULL,
  SCHDUL_BEGINDE CHAR(20) NULL,
  SCHDUL_ENDDE CHAR(20) NULL,
  SCHDUL_NM VARCHAR(255) NULL,
  SCHDUL_CN VARCHAR(2500) NULL,
  SCHDUL_PLACE VARCHAR(255) NULL,
  SCHDUL_IPCR_CODE CHAR(1) NULL,
  SCHDUL_CHARGER_ID VARCHAR(20) NULL,
  ATCH_FILE_ID CHAR(20) NULL,
  FRST_REGISTER_ID VARCHAR(20) NULL,
  FRST_REGIST_PNTTM DATETIME NULL,
  LAST_UPDUSR_ID VARCHAR(20) NULL,
  LAST_UPDT_PNTTM DATETIME NULL,
  REPTIT_SE_CODE CHAR(3) NULL,
  CONSTRAINT COMTNSCHDULINFO_PK PRIMARY KEY (SCHDUL_ID)
);



CREATE TABLE COMTNFILE (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  CREAT_DT DATETIME NOT NULL,
  USE_AT CHAR(1) NULL,
  CONSTRAINT COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
);



CREATE TABLE COMTNFILEDETAIL (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  FILE_SN NUMERIC(10) NOT NULL,
  FILE_STRE_COURS VARCHAR(2000) NOT NULL,
  STRE_FILE_NM VARCHAR(255) NOT NULL,
  ORIGNL_FILE_NM VARCHAR(255) NULL,
  FILE_EXTSN VARCHAR(20) NOT NULL,
  FILE_CN MEDIUMTEXT NULL,
  FILE_SIZE NUMERIC(8) NULL,
  CONSTRAINT COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID, FILE_SN),
  CONSTRAINT COMTNFILEDETAIL_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
);



CREATE OR REPLACE VIEW COMVNUSERMASTER ( ESNTL_ID,USER_ID,PASSWORD,USER_NM,USER_ZIP,USER_ADRES,USER_EMAIL,GROUP_ID, USER_SE, ORGNZT_ID ) 
AS  
        SELECT ESNTL_ID, MBER_ID,PASSWORD,MBER_NM,ZIP,ADRES,MBER_EMAIL_ADRES,' ','GNR' AS USER_SE, ' ' ORGNZT_ID
        FROM COMTNGNRLMBER
    UNION ALL
        SELECT ESNTL_ID,EMPLYR_ID,PASSWORD,USER_NM,ZIP,HOUSE_ADRES,EMAIL_ADRES,GROUP_ID ,'USR' AS USER_SE, ORGNZT_ID
        FROM COMTNEMPLYRINFO
    UNION ALL
        SELECT ESNTL_ID,ENTRPRS_MBER_ID,ENTRPRS_MBER_PASSWORD,CMPNY_NM,ZIP,ADRES,APPLCNT_EMAIL_ADRES,' ' ,'ENT' AS USER_SE, ' ' ORGNZT_ID
        FROM COMTNENTRPRSMBER 
;